# Goal:
For new changed data, `post_data_v2.json`, run the **numerical_only** model and then do the **error taxonomy**. And then if applicable, do the feature engineering

In [30]:
import json
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import random

In [31]:
df = pd.read_csv("../../../data/post_quality/processed/post_quality_fe2_fixed.csv")
df

,title,body,code,label,text,title_len,body_len,num_exclamations,questions_per_100_words,has_multiple_paras,has_exclamations,log_num_para,word_count,avg_word_len,unique_word_ratio,has_code,log_btt,log_btt_x_has_questions,question_density_per_para,first_person_ratio
0,Why are genetic differences in appearance and ...,"I mean, different human races have lived in di...",NaN,1,Why are genetic differences in appearance and ...,188,210,0,2.666667,0,0,0.693147,63,5.349206,0.777778,0,0.110111,0.110111,2.0,0.015625
1,I changed a road sign to make my commute easie...,On my daily commute there was very inconvenien...,NaN,0,I changed a road sign to make my commute easie...,61,1185,0,0.000000,1,0,1.791759,255,3.894118,0.552941,0,2.951207,0.000000,0.0,0.065385
2,What’s a skill that sounds boring but is actua...,"Some skills don’t sound exciting at first, but...",NaN,1,What’s a skill that sounds boring but is actua...,58,309,0,1.333333,0,0,0.693147,62,4.951613,0.806452,0,1.659035,1.659035,1.0,0.014925
3,I can post!,So...\n😭💔😶‍🌫️🥱😮‍💨🙄😒😓😥☹️\nI'm tired.,NaN,0,I can post!\n\nSo...\n😭💔😶‍🌫️🥱😮‍💨🙄😒😓😥☹️\nI'm ti...,11,33,1,0.000000,1,1,1.386294,7,5.571429,1.000000,0,1.041454,0.000000,0.0,0.285714
4,My biggest fear is Alzheimer’s,"Not for me, for my mom.\nI don’t think I could...",NaN,0,"My biggest fear is Alzheimer’s\n\nNot for me, ...",30,133,0,0.000000,1,0,1.098612,33,4.000000,0.787879,0,1.463853,0.000000,0.0,0.142857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,I’m (27f) 80% sure my roommate(30m) wants to s...,"I wanna sleep with him too, honestly he’s tota...",NaN,1,I’m (27f) 80% sure my roommate(30m) wants to s...,58,762,0,0.000000,0,0,0.693147,157,4.235669,0.719745,0,2.559721,0.000000,0.0,0.120482
71,"Vegas didn’t evolve, it got murdered by MGM an...","Old Vegas: mob skimmed the drop, but drinks we...",NaN,1,"Vegas didn’t evolve, it got murdered by MGM an...",78,889,0,0.000000,1,0,1.791759,179,4.413408,0.698324,0,2.421774,0.000000,0.0,0.005435
72,Beginner Next.js Authentication Project — Look...,Hi everyone 👋\n\nI’m currently learning Next.j...,NaN,1,Beginner Next.js Authentication Project — Look...,83,957,1,0.000000,1,1,3.295837,147,6.034014,0.768707,0,2.434031,0.000000,0.0,0.044872
73,Say something in a language other than English...,NaN,NaN,0,Say something in a language other than English...,92,0,0,0.000000,0,0,0.693147,17,4.470588,0.941176,0,-4.532599,-0.000000,0.0,0.000000
74,Add a festive snow effect this Christmas with ...,Hello r/reactjs!\n\nSprinkling some snow acros...,import { SnowOverlay } from 'react-snow-overla...,0,Add a festive snow effect this Christmas with ...,68,502,2,0.000000,1,1,2.302585,87,5.528736,0.839080,1,1.986484,0.000000,0.0,0.037736

In [63]:
df.columns

Index(['title', 'body', 'code', 'label', 'text', 'title_len', 'body_len',
       'num_exclamations', 'questions_per_100_words', 'has_multiple_paras',
       'has_exclamations', 'log_num_para', 'word_count', 'avg_word_len',
       'unique_word_ratio', 'has_code', 'log_btt', 'log_btt_x_has_questions',
       'question_density_per_para', 'first_person_ratio', 'is_likely_factual'],
      dtype='object')

In [32]:
for col in df.columns:
    print(f"Number of null value in '{col}' column is {df[col].isnull().sum()}")

Number of null value in 'title' column is 0
Number of null value in 'body' column is 23
Number of null value in 'code' column is 69
Number of null value in 'label' column is 0
Number of null value in 'text' column is 0
Number of null value in 'title_len' column is 0
Number of null value in 'body_len' column is 0
Number of null value in 'num_exclamations' column is 0
Number of null value in 'questions_per_100_words' column is 0
Number of null value in 'has_multiple_paras' column is 0
Number of null value in 'has_exclamations' column is 0
Number of null value in 'log_num_para' column is 0
Number of null value in 'word_count' column is 0
Number of null value in 'avg_word_len' column is 0
Number of null value in 'unique_word_ratio' column is 0
Number of null value in 'has_code' column is 0
Number of null value in 'log_btt' column is 0
Number of null value in 'log_btt_x_has_questions' column is 0
Number of null value in 'question_density_per_para' column is 0
Number of null value in 'first_person_ratio' column is 0

In [33]:
df['body'] = df['body'].fillna('')
df['code'] = df['code'].fillna('')

In [34]:
for col in df.columns:
    print(f"Number of null value in '{col}' column is {df[col].isnull().sum()}")

Number of null value in 'title' column is 0
Number of null value in 'body' column is 0
Number of null value in 'code' column is 0
Number of null value in 'label' column is 0
Number of null value in 'text' column is 0
Number of null value in 'title_len' column is 0
Number of null value in 'body_len' column is 0
Number of null value in 'num_exclamations' column is 0
Number of null value in 'questions_per_100_words' column is 0
Number of null value in 'has_multiple_paras' column is 0
Number of null value in 'has_exclamations' column is 0
Number of null value in 'log_num_para' column is 0
Number of null value in 'word_count' column is 0
Number of null value in 'avg_word_len' column is 0
Number of null value in 'unique_word_ratio' column is 0
Number of null value in 'has_code' column is 0
Number of null value in 'log_btt' column is 0
Number of null value in 'log_btt_x_has_questions' column is 0
Number of null value in 'question_density_per_para' column is 0
Number of null value in 'first_person_ratio' column is 0

## Running the numerical only model with new data

In [35]:
## Let's build a helper function to make error_df
import pandas as pd

def build_error_df(df_test, y_true, y_pred, model_name):
    out = df_test.copy()
    out['true_label'] = y_true
    out['pred_label'] = y_pred
    out['correct'] = y_true == y_pred
    out['model'] = model_name
    return out

In [36]:
## Generic function to split df in same test and train
from sklearn.model_selection import train_test_split


def split_df(
    df,
    label_col,
    test_size=0.2,
    random_state=52,
    stratify=True
):
    """
    Splits dataframe into train and test sets.

    Returns
    -------
    df_train : pd.DataFrame
    df_test : pd.DataFrame
    """

    df = df.reset_index(drop=True)

    stratify_col = df[label_col] if stratify else None

    train_idx, test_idx = train_test_split(
        df.index,
        test_size=test_size,
        random_state=random_state,
        stratify=stratify_col
    )

    df_train = df.loc[train_idx]
    df_test = df.loc[test_idx]

    return df_train, df_test

In [37]:
## Running numerical only model
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,accuracy_score


def run_numerical_model(
    df_train,
    df_test,
    label_col,
    num_cols=None,
    model=None,
    scaler=None,
    model_name="numerical_only"
):
    """
    Trains and evaluates a numerical-only classification model.

    Returns
    -------
    dict with:
        - model
        - scaler
        - classification_report
        - errors_df
        - y_pred
    """

    if num_cols is None:
        num_cols = df_train.select_dtypes(include="number").columns.tolist()
        num_cols.remove(label_col)

    if scaler is None:
        scaler = StandardScaler()

    if model is None:
        model = LogisticRegression(
            max_iter=2000,
            class_weight="balanced"
        )

    X_train = scaler.fit_transform(df_train[num_cols])
    X_test = scaler.transform(df_test[num_cols])

    y_train = df_train[label_col]
    y_test = df_test[label_col]

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    report = classification_report(y_test, y_pred)

    errors_df = build_error_df(
        df_test=df_test,
        y_true=y_test,
        y_pred=y_pred,
        model_name=model_name
    )

    errors_df['error_type'] = ''
    errors_df['error_subtype'] = ''
    errors_df['notes'] = ''

    return {
        "model": model,
        "scaler": scaler,
        "classification_report": report,
        "errors_df": errors_df,
        "accuracy":accuracy_score(y_test,y_pred),
        "y_pred": y_pred
    }

In [38]:
## Function to get error across k-folds
import pandas as pd
from sklearn.model_selection import StratifiedKFold

def run_k_fold_error_analysis(df:pd.DataFrame, n_splits=5, label_col='label'):
    skf = StratifiedKFold(
        n_splits=n_splits,
        shuffle=True,
        random_state=42
    )
    
    all_errors = []
    
    for fold, (train_idx, test_idx) in enumerate(skf.split(df, df[label_col])):
        train_df = df.iloc[train_idx].copy()
        test_df = df.iloc[test_idx].copy()
        
        result = run_numerical_model(
            train_df,
            test_df,
            label_col=label_col
        )
        
        errors_df = result['errors_df'].copy()
        
        errors_df['fold'] = fold
        
        all_errors.append(errors_df)
    
    errors_all = pd.concat(all_errors).reset_index(drop=True)
    
    errors_only = errors_all[errors_all['correct'] == False]
    
    errors_all['error_type'] = 'N/A'  
    errors_all['error_subtype'] = 'N/A'  
    errors_all['notes'] = ''  
    
    true_label_counts = errors_only['true_label'].value_counts()
    pred_label_counts = errors_only['pred_label'].value_counts()
    error_group_counts = errors_only.groupby(['true_label', 'pred_label']).size()
    
    return {
        'errors_all': errors_all,
        'errors_only': errors_only,
        'true_label_counts': true_label_counts,
        'pred_label_counts': pred_label_counts,
        'error_group_counts': error_group_counts
    }

### Running numerical model on single split to get the errors and start doing error taxonomy manually

In [39]:
df_train, df_test = split_df(df,'label')
result = run_numerical_model(df_train,df_test,'label')
df_train.shape,df_test.shape

((60, 20), (15, 20))

In [40]:
all_result = result['errors_df']
error_only = all_result[all_result['correct'] == False].copy()
error_only

,title,body,code,label,text,title_len,body_len,num_exclamations,questions_per_100_words,has_multiple_paras,...,log_btt_x_has_questions,question_density_per_para,first_person_ratio,true_label,pred_label,correct,model,error_type,error_subtype,notes
70,I’m (27f) 80% sure my roommate(30m) wants to s...,"I wanna sleep with him too, honestly he’s tota...",,1,I’m (27f) 80% sure my roommate(30m) wants to s...,58,762,0,0.000000,0,...,0.000000,0.0,0.120482,1,0,False,numerical_only,,,
1,I changed a road sign to make my commute easie...,On my daily commute there was very inconvenien...,,0,I changed a road sign to make my commute easie...,61,1185,0,0.000000,1,...,0.000000,0.0,0.065385,0,2,False,numerical_only,,,
6,What did you gain by getting out of your home ...,,,2,What did you gain by getting out of your home ...,76,0,0,1.333333,0,...,-4.343805,1.0,0.000000,2,1,False,numerical_only,,,
66,19F Exhausted New mom not much help from parents.,"Hi i'm a 19f new mom, and I gave birth to my d...",,2,19F Exhausted New mom not much help from paren...,49,1093,0,0.000000,1,...,0.000000,0.0,0.094170,2,0,False,numerical_only,,,
71,"Vegas didn’t evolve, it got murdered by MGM an...","Old Vegas: mob skimmed the drop, but drinks we...",,1,"Vegas didn’t evolve, it got murdered by MGM an...",78,889,0,0.000000,1,...,0.000000,0.0,0.005435,1,2,False,numerical_only,,,
42,Where did the girls on Epstein's Island come f...,,,0,Where did the girls on Epstein's Island come f...,96,0,0,4.000000,0,...,-4.574711,3.0,0.000000,0,2,False,numerical_only,,,

## Error Taxonomy

All model errors are categorized into one of four fixed error categories.  
Each category may have one or more subtypes to support precise diagnosis and targeted iteration.

---

### **Category A — Label Ambiguity (Human Disagreement)**

**Definition**  
Errors where humans themselves can reasonably disagree on the correct label, even with full context.

These errors are *inherently ambiguous* and are not considered model failures.

#### **A1. Boundary Ambiguity**
- The post lies near the boundary between two adjacent labels.
- A reasonable annotator could choose either label.
- Example: A thoughtful but brief discussion post (label 1 vs label 2).

**Action**: Accept as irreducible noise. Do not tune or engineer features.

#### **A2. Multi-Intent Ambiguity**
- The post satisfies multiple labeling intents (e.g., personal reflection + general discussion).
- Label choice depends on which intent is prioritized.

**Action**: Accept ambiguity. Optionally document for future soft-labeling.

---

### **Category B — Feature–Label Mismatch**

**Definition**  
The model is using valid, learnable signals, but those signals do not align with how labels are defined.

This indicates a mismatch between feature proxies and labeling logic.

#### **B1. Structural Proxy Mismatch**
- Model relies heavily on length, formatting, or punctuation.
- Structural cues dominate semantic intent.
- Example: Long but low-quality post predicted as high quality.

**Action**: Adjust feature weighting or introduce counterbalancing features.

#### **B2. Engagement Proxy Mismatch**
- Model equates engagement-bait signals with quality.
- Emotionally charged or controversial posts are overvalued.

**Action**: Clarify label definition or add engagement-neutral indicators.

---

### **Category C — Data Sparsity / Instability**

**Definition**  
Errors caused by insufficient or imbalanced data, leading to unstable learned rules.

These errors may resolve naturally as data grows.

#### **C1. Rare Pattern Underrepresentation**
- Certain post types appear too infrequently to learn stable behavior.
- Predictions vary significantly across splits or folds.

**Action**: Add more data. Avoid hard rules.

#### **C2. Feature Sparsity**
- Feature fires for very few samples.
- Minimal or inconsistent impact across runs.

**Action**: Keep feature if conceptually sound, but do not expect immediate gains.

---

### **Category D — Representational Gap (Semantic / Pragmatic)**

**Definition**  
Errors caused by limitations of numerical and shallow text features.
The model cannot capture semantic intent or pragmatic meaning.

These errors are **out of scope** for the current modeling approach.

#### **D1. Pragmatic Intent Gap**
- Requires understanding *why* the question is being asked.
- Depends on advice-seeking, reflection, or emotional intent.

**Action**: Acknowledge limitation. Requires embeddings or discourse modeling.

#### **D2. Discourse-Level Meaning**
- Meaning emerges only across multiple sentences or paragraphs.
- Narrative structure is essential.

**Action**: Out of scope for numerical-only models.

#### **D3. Structural Bias Masking Intent**
- Model overweights post length over intent.
- Title-only open-ended posts are undervalued.
- Title + body posts are overvalued.

**Action**: Document and freeze. Do not over-engineer.

---

## Taxonomy Usage Rules

- Each error must be assigned **exactly one category**.
- Subtypes are used for diagnostic clarity, not optimization pressure.
- Category D errors are documented, not “fixed.”
- Feature engineering is only justified for Category B or C errors.

In [41]:
error_only.iloc[0, error_only.columns.get_loc('error_type')] = 'D'
error_only.iloc[0, error_only.columns.get_loc('error_subtype')] = 'Pragmatic Intent Gap'
error_only.iloc[0, error_only.columns.get_loc('notes')] = 'The numerical-only model fails to detect implicit advice-seeking intent when it is not expressed through explicit interrogative structure. Although the post contains strong emotional context, unresolved conflict, and an explicit statement of openness to advice, the model interprets the lack of a question mark and the presence of first-person narration as indicators of low-quality venting (label 0). This reflects a limitation in capturing pragmatic intent and social context rather than a feature-label mismatch or data sparsity issue. Resolving this error would require semantic or discourse-level representations beyond the scope of numerical-only features.'

In [42]:
error_only.iloc[1, error_only.columns.get_loc('error_type')] = 'D'
error_only.iloc[1, error_only.columns.get_loc('error_subtype')] = 'Representational Gap'
error_only.iloc[1, error_only.columns.get_loc('notes')] = 'The numerical-only model incorrectly classifies a long anecdotal narrative as a discussion-oriented post (label 2). The post contains detailed storytelling and multi-paragraph structure but lacks advice-seeking, abstraction, or an open-ended inquiry. The model conflates narrative complexity and length with conceptual depth, failing to distinguish between personal anecdotes intended for reactions and posts meant to elicit discussion. This reflects a limitation in modeling author intent rather than a data sparsity or feature-label mismatch issue.'

In [43]:
error_only.iloc[2, error_only.columns.get_loc('error_type')] = 'B'
error_only.iloc[2, error_only.columns.get_loc('error_subtype')] = 'Discussion Breadth Undervalued'
error_only.iloc[2, error_only.columns.get_loc('notes')] = 'The numerical-only model correctly detects the post as a question but systematically undervalues title-only posts by capping them at a moderate quality score (label 1). The model relies on verbosity and body length as proxies for engagement potential, failing to recognize that concise, open-ended questions can generate highly diverse and discussion-rich responses. This reflects a mismatch between model features and the intended label definition, where conceptual openness and response diversity outweigh text length.'

In [44]:
error_only.iloc[3, error_only.columns.get_loc('error_type')] = 'D'
error_only.iloc[3, error_only.columns.get_loc('error_subtype')] = 'Pragmatic Intent Gap'
error_only.iloc[3, error_only.columns.get_loc('notes')] = 'The numerical-only model fails to detect advice-seeking intent when it is expressed implicitly rather than through explicit question syntax. Despite the post clearly stating “I could really use some advice” and presenting structured pain points, the model predicts the lowest quality label due to absence of question marks and dominant first-person narrative. This reflects an inability to capture pragmatic intent, emotional vulnerability, and social support requests using surface-level features.'

In [45]:
error_only.iloc[4, error_only.columns.get_loc('error_type')] = 'A'
error_only.iloc[4, error_only.columns.get_loc('error_subtype')] = 'Opinionated Rant with High Discussion Potential'
error_only.iloc[4, error_only.columns.get_loc('notes')] = 'The post is a strongly opinionated rant that invites debate and commentary but does not explicitly ask a question or request advice. Reasonable annotators may disagree whether such posts should be classified as moderate (label 1) or high engagement (label 2). The model prediction of label 2 is defensible, indicating ambiguity in labeling guidelines rather than a clear model failure.'

In [46]:
error_only.iloc[5, error_only.columns.get_loc('error_type')] = 'B'
error_only.iloc[5, error_only.columns.get_loc('error_subtype')] = 'Factual Question Misinterpreted as Discussion'
error_only.iloc[5, error_only.columns.get_loc('notes')] = 'The post is a factual, investigative question seeking convergent answers about a known real-world event. While the topic is sensitive and publicly discussed, responses are primarily informational rather than opinion-based or exploratory.The model incorrectly predicts high discussion value (label 2), likely relying on surface cues such as the presence of a question, topic salience, and lack of personal narrative. However, these signals do not correspond to the labeling definition of high engagement, which depends on diversity of reasonable responses rather than controversy alone.This represents a mismatch between the model’s learned features and the intended semantic meaning of the labels.'

In [47]:
error_only

,title,body,code,label,text,title_len,body_len,num_exclamations,questions_per_100_words,has_multiple_paras,...,log_btt_x_has_questions,question_density_per_para,first_person_ratio,true_label,pred_label,correct,model,error_type,error_subtype,notes
70,I’m (27f) 80% sure my roommate(30m) wants to s...,"I wanna sleep with him too, honestly he’s tota...",,1,I’m (27f) 80% sure my roommate(30m) wants to s...,58,762,0,0.000000,0,...,0.000000,0.0,0.120482,1,0,False,numerical_only,D,Pragmatic Intent Gap,The numerical-only model fails to detect impli...
1,I changed a road sign to make my commute easie...,On my daily commute there was very inconvenien...,,0,I changed a road sign to make my commute easie...,61,1185,0,0.000000,1,...,0.000000,0.0,0.065385,0,2,False,numerical_only,D,Representational Gap,The numerical-only model incorrectly classifie...
6,What did you gain by getting out of your home ...,,,2,What did you gain by getting out of your home ...,76,0,0,1.333333,0,...,-4.343805,1.0,0.000000,2,1,False,numerical_only,B,Discussion Breadth Undervalued,The numerical-only model correctly detects the...
66,19F Exhausted New mom not much help from parents.,"Hi i'm a 19f new mom, and I gave birth to my d...",,2,19F Exhausted New mom not much help from paren...,49,1093,0,0.000000,1,...,0.000000,0.0,0.094170,2,0,False,numerical_only,D,Pragmatic Intent Gap,The numerical-only model fails to detect advic...
71,"Vegas didn’t evolve, it got murdered by MGM an...","Old Vegas: mob skimmed the drop, but drinks we...",,1,"Vegas didn’t evolve, it got murdered by MGM an...",78,889,0,0.000000,1,...,0.000000,0.0,0.005435,1,2,False,numerical_only,A,Opinionated Rant with High Discussion Potential,The post is a strongly opinionated rant that i...
42,Where did the girls on Epstein's Island come f...,,,0,Where did the girls on Epstein's Island come f...,96,0,0,4.000000,0,...,-4.574711,3.0,0.000000,0,2,False,numerical_only,B,Factual Question Misinterpreted as Discussion,"The post is a factual, investigative question ..."

In [48]:
error_only['error_type'].value_counts()

error_type
D    3
B    2
A    1
Name: count, dtype: int64

In [49]:
error_only['error_subtype'].value_counts()

error_subtype
Pragmatic Intent Gap                               2
Representational Gap                               1
Discussion Breadth Undervalued                     1
Opinionated Rant with High Discussion Potential    1
Factual Question Misinterpreted as Discussion      1
Name: count, dtype: int64

## Cross-validation sanity check for error taxonomy

After completing error taxonomy on a single stratified split, I am going to perform a 5-fold stratified cross-validation pass to verify whether the identified error subtypes are stable across different train–test partitions.

The goal of this step is not to discover new error categories, but to confirm whether the observed failures are systematic properties of the model rather than artifacts of a specific split.

For each fold:
- I will train the same numerical-only model
- Collect misclassified samples
- Assign error categories and subtypes using the established taxonomy

If an error subtype recurs across multiple folds, it will be treated as a stable modeling limitation.
If it appears only once, it will be considered sparse noise and deprioritized.

In [50]:
taxonomy_k_fold_analysis = run_k_fold_error_analysis(df)

In [51]:
k_fold_errors = taxonomy_k_fold_analysis['errors_only']
k_fold_errors.shape

(39, 28)

In [52]:
k_fold_errors

,title,body,code,label,text,title_len,body_len,num_exclamations,questions_per_100_words,has_multiple_paras,...,question_density_per_para,first_person_ratio,true_label,pred_label,correct,model,error_type,error_subtype,notes,fold
0,"Be honest, what do you think comes after death?",,,1,"Be honest, what do you think comes after death...",47,0,0,1.333333,0,...,1.000000,0.000000,1,0,False,numerical_only,,,,0
2,marketo form validation with fetch,I added a fetch function to do some hidden val...,form.onSubmit(async function(form) {\n let ...,2,marketo form validation with fetch\n\nI added ...,34,248,0,0.000000,0,...,0.000000,0.060000,2,0,False,numerical_only,,,,0
3,A simple rule to help build your own thing,Let me start off by saying that work as a web ...,,0,A simple rule to help build your own thing\n\n...,42,1243,0,1.333333,1,...,0.076923,0.068000,0,1,False,numerical_only,,,,0
4,Learn programming as an absolute beginner,I’m a complete outsider here I’ve always wante...,,1,Learn programming as an absolute beginner\n\nI...,41,299,0,4.000000,0,...,3.000000,0.078125,1,2,False,numerical_only,,,,0
6,How would you feel if your country banned Burk...,,,1,How would you feel if your country banned Burk...,73,0,0,1.333333,0,...,1.000000,0.000000,1,0,False,numerical_only,,,,0
7,Professionals who enter people's homes (plumbe...,,,1,Professionals who enter people's homes (plumbe...,187,0,0,1.333333,0,...,1.000000,0.000000,1,0,False,numerical_only,,,,0
12,What’s a subtle sign of very low intelligence?,I’ve been thinking about this lately and wante...,,1,What’s a subtle sign of very low intelligence?...,46,229,0,2.666667,0,...,2.000000,0.041667,1,2,False,numerical_only,,,,0
18,"How can i stop idealising a better, fulfilling...",Title might be confusing but I just want to kn...,,1,"How can i stop idealising a better, fulfilling...",79,1090,0,2.666667,1,...,0.333333,0.071429,1,2,False,numerical_only,,,,1
19,Honeypot fields still work surprisingly well,Hidden input field. Bots fill it. Humans can't...,,2,Honeypot fields still work surprisingly well\n...,44,229,0,1.333333,0,...,1.000000,0.000000,2,1,False,numerical_only,,,,1
24,Where did the girls on Epstein's Island come f...,,,0,Where did the girls on Epstein's Island come f...,96,0,0,4.000000,0,...,3.000000,0.000000,0,2,False,numerical_only,,,,1
25,CMV: I believe a big majority of social media ...,I think a lot of bad or overtly loud internet ...,,2,CMV: I believe a big majority of social media ...,69,625,0,0.000000,0,...,0.000000,0.024000,2,1,False,numerical_only,,,,1
28,Is there anything biologically that stops a pa...,Alright kinda hard to explain but I was thinki...,,2,Is there anything biologically that stops a pa...,113,535,0,2.666667,0,...,2.000000,0.025862,2,1,False,numerical_only,,,,1
29,Beginner Next.js Authentication Project — Look...,Hi everyone 👋\n\nI’m currently learning Next.j...,,1,Beginner Next.js Authentication Project — Look...,83,957,1,0.000000,1,...,0.000000,0.044872,1,0,False,numerical_only,,,,1
30,What’s a skill that sounds boring but is actua...,"Some skills don’t sound exciting at first, but...",,1,What’s a skill that sounds boring but is actua...,58,309,0,1.333333,0,...,1.000000,0.014925,1,2,False,numerical_only,,,,2
31,I can post!,So...\n😭💔😶‍🌫️🥱😮‍💨🙄😒😓😥☹️\nI'm tired.,,0,I can post!\n\nSo...\n😭💔😶‍🌫️🥱😮‍💨🙄😒😓😥☹️\nI'm ti...,11,33,1,0.000000,1,...,0.000000,0.285714,0,1,False,numerical_only,,,,2
32,PSA: When you reach out to a co-worker on slac...,I’m going to spend the next 12 minutes distrac...,,0,PSA: When you reach out to a co-worker on slac...,149,403,0,0.000000,1,...,0.000000,0.039604,0,1,False,numerical_only,,,,2
34,What habits of girls did you only discover aft...,,,1,What habits of girls did you only discover aft...,78,0,0,1.333333,0,...,1.000000,0.000000,1,0,False,numerical_only,,,,2
35,Advice: My partner and I may have conceived.,Disclaimer; I (16M) know nothing about s*x and...,,2,Advice: My partner and I may have conceived.\n...,44,2120,1,0.000000,1,...,0.000000,0.050251,2,1,False,numerical_only,,,,2
37,"Hey guys, has anyone ever had one of those wei...","So a couple years ago, I was on a solo trip to...",,1,"Hey guys, has anyone ever had one of those wei...",103,1143,0,6.666667,1,...,1.000000,0.058333,1,2,False,numerical_only,,,,2
39,what would the modern day versions of the Gree...,,,1,what would the modern day versions of the Gree...,61,0,0,1.333333,0,...,1.000000,0.000000,1,0,False,numerical_only,,,,2
40,Sharks can sense electrical impulses. Because ...,,,2,Sharks can sense electrical impulses. Because ...,288,0,0,2.666667,0,...,2.000000,0.000000,2,1,False,numerical_only,,,,2
41,"how do you grab life by its horn and live a ""s...",,,2,"how do you grab life by its horn and live a ""s...",85,0,0,1.333333,0,...,1.000000,0.000000,2,0,False,numerical_only,,,,2
42,Pygame catch the falling object(you can use as...,,import pygame\nimport sys\nimport time\nimport...,0,Pygame catch the falling object(you can use as...,71,0,0,0.000000,0,...,0.000000,0.000000,0,1,False,numerical_only,,,,2
44,Add a festive snow effect this Christmas with ...,Hello r/reactjs!\n\nSprinkling some snow acros...,import { SnowOverlay } from 'react-snow-overla...,0,Add a festive snow effect this Christmas with ...,68,502,2,0.000000,1,...,0.000000,0.037736,0,1,False,numerical_only,,,,2
45,I changed a road sign to make my commute easie...,On my daily commute there was very inconvenien...,,0,I changed a road sign to make my commute easie...,61,1185,0,0.000000,1,...,0.000000,0.065385,0,2,False,numerical_only,,,,3
47,What did you gain by getting out of your home ...,,,2,What did you gain by getting out of your home ...,76,0,0,1.333333,0,...,1.000000,0.000000,2,1,False,numerical_only,,,,3
50,I got called a fascist today.,So I was on tiktok and a post came about on a ...,,2,I got called a fascist today.\n\nSo I was on t...,29,531,0,4.000000,0,...,3.000000,0.095652,2,1,False,numerical_only,,,,3
52,How do couples navigate mismatched bedtimes? B...,My boyfriend (35m) and I (28f) have been toget...,,2,How do couples navigate mismatched bedtimes? B...,99,1545,0,5.333333,1,...,0.800000,0.107034,2,1,False,numerical_only,,,,3
54,Blacked out and ruined my college life.,"I (18,m) was always a very social kind of pers...",,1,Blacked out and ruined my college life.\n\nI (...,39,1817,0,1.333333,1,...,0.200000,0.102273,1,2,False,numerical_only,,,,3
56,I’m dead soon,Hi I’m Macy and my parents are killing me in l...,,0,I’m dead soon\n\nHi I’m Macy and my parents ar...,13,1703,0,0.000000,1,...,0.000000,0.066860,0,2,False,numerical_only,,,,3
57,I wanna sudoku,God I wanna sudoku. Was contemplating going to...,,0,I wanna sudoku\n\nGod I wanna sudoku. Was cont...,14,2658,0,0.000000,0,...,0.000000,0.094270,0,2,False,numerical_only,,,,3
58,"Vegas didn’t evolve, it got murdered by MGM an...","Old Vegas: mob skimmed the drop, but drinks we...",,1,"Vegas didn’t evolve, it got murdered by MGM an...",78,889,0,0.000000,1,...,0.000000,0.005435,1,2,False,numerical_only,,,,3
60,Stripe Native crashes on google pixel device,I’m integrating Stripe PaymentSheet (React Nat...,const openPaymentSheet = async () => {\n try ...,2,Stripe Native crashes on google pixel device\n...,44,331,0,0.000000,1,...,0.000000,0.051724,2,0,False,numerical_only,,,,4
61,"""American Problems"" which doesn't exist anywhe...",Have noticed most of the americans are having ...,,0,"""American Problems"" which doesn't exist anywhe...",54,175,0,2.666667,0,...,2.000000,0.000000,0,2,False,numerical_only,,,,4
66,Can't afford to live and I've exhausted all ot...,So I've been sitting here for the past three d...,,0,Can't afford to live and I've exhausted all ot...,57,333,0,2.666667,0,...,2.000000,0.137500,0,1,False,numerical_only,,,,4
68,Living in a foreign country is taking its tow,"I love the country I choose to live, since it ...",,1,Living in a foreign country is taking its tow\...,45,285,0,0.000000,1,...,0.000000,0.032258,1,0,False,numerical_only,,,,4
69,Approaches to testing a unit of code that make...,I'm writing some unit tests for a class member...,SomeClass::unit_under_test() {\n this->f();...,1,Approaches to testing a unit of code that make...,73,706,0,1.333333,0,...,1.000000,0.047945,1,2,False,numerical_only,,,,4
73,Men's public restrooms are laid out all wrong....,,,0,Men's public restrooms are laid out all wrong....,145,0,0,0.000000,0,...,0.000000,0.000000,0,2,False,numerical_only,,,,4
74,19F Exhausted New mom not much help from parents.,"Hi i'm a 19f new mom, and I gave birth to my d...",,2,19F Exhausted New mom not much help from paren...,49,1093,0,0.000000,1,...,0.000000,0.094170,2,0,False,numerical_only,,,,4

In [53]:
## Saving the error
error_only.to_csv("../../../data/post_quality/processed/numerical_error_taxonomy_v2.csv",index=False)

## Error pattern consolidation (pre-feature engineering)

After reviewing misclassified samples, several consistent structural patterns emerge. These patterns suggest that the numerical-only model relies heavily on surface-level cues (length, presence of question marks, paragraph structure) rather than semantic intent.

Observed hypotheses:

1. Title-only open-ended questions are consistently downgraded to label 1, regardless of their true discussion breadth.
2. Title-only non-question posts are consistently predicted as label 0.
3. Open-ended posts with both title and body are consistently overvalued as label 2.
4. Long posts with low first-person pronoun usage are frequently predicted as label 2, even when discussion breadth is moderate.
5. The model does not distinguish between factual-convergent questions and opinion-divergent discussions, treating both as high discussion potential.

These hypotheses will guide targeted feature engineering and further validation.

# Feature Engineering 3

In [54]:
from sklearn.model_selection import StratifiedKFold
import numpy as np
import pandas as pd


def evaluate_model_with_feature_and_changes(
    df,
    target_label,
    feature_to_check,
    n_splits=5,
    random_state=42,
    text_cols=("title", "body")
):
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)

    acc_with_feature = []
    acc_without_feature = []
    open_acc_with = []
    open_acc_without = []

    changed_rows_all_folds = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(df, df[target_label])):
        train_df = df.iloc[train_idx].copy()
        test_df = df.iloc[test_idx].copy()

        # -----------------------
        # WITH FEATURE
        # -----------------------
        result_with = run_numerical_model(train_df, test_df, target_label)
        acc_with_feature.append(result_with["accuracy"])

        errors_with = result_with["errors_df"]

        # -----------------------
        # WITHOUT FEATURE
        # -----------------------
        train_df_no = train_df.drop(columns=[feature_to_check], errors="ignore")
        test_df_no = test_df.drop(columns=[feature_to_check], errors="ignore")

        result_without = run_numerical_model(train_df_no, test_df_no, target_label)
        acc_without_feature.append(result_without["accuracy"])

        errors_without = result_without["errors_df"]

        # -----------------------
        # OPEN-ENDED accuracy (your existing logic)
        # -----------------------
        open_test = test_df[test_df[feature_to_check] == 1]

        if len(open_test) > 0:
            wrong_open_with = errors_with[
                (~errors_with["correct"]) &
                (errors_with.index.isin(open_test.index))
            ].shape[0]

            wrong_open_without = errors_without[
                (~errors_without["correct"]) &
                (errors_without.index.isin(open_test.index))
            ].shape[0]

            open_acc_with.append(1 - wrong_open_with / len(open_test))
            open_acc_without.append(1 - wrong_open_without / len(open_test))

        # =======================
        # FIND CHANGED PREDICTIONS
        # =======================

        merged = (
            test_df
            .loc[:, list(text_cols) + [feature_to_check]]
            .copy()
        )

        merged["true_label"] = df.loc[test_idx, target_label]
        merged["pred_without_feature"] = errors_without["pred_label"]
        merged["pred_with_feature"] = errors_with["pred_label"]

        # Keep only rows where prediction changed
        changed = merged[
            merged["pred_with_feature"] != merged["pred_without_feature"]
        ].copy()

        if not changed.empty:
            changed["fold"] = fold
            changed_rows_all_folds.append(changed)

    # Combine all folds
    changed_df = (
        pd.concat(changed_rows_all_folds, axis=0)
        if changed_rows_all_folds
        else pd.DataFrame()
    )

    results = {
        "overall_accuracy_with_feature": np.mean(acc_with_feature),
        "overall_accuracy_without_feature": np.mean(acc_without_feature),
        "open_ended_accuracy_with_feature": np.mean(open_acc_with),
        "open_ended_accuracy_without_feature": np.mean(open_acc_without),
        "changed_predictions_df": changed_df
    }

    return results

## Feature #1: factual vs opinion divergence
#### Concept (human language)
* Factual questions -> converge to one answer
* Opinion questions -> branch into many answers

In [55]:
FACTUAL_STARTS = (
    "who is", "what is", "where is", "when did", "how many",
    "how much", "what year", "what date","who's","what's","where's"
)

def is_likely_factual(text):
    text = text.lower().strip()
    for fs in FACTUAL_STARTS:
        if text.startswith(fs):
            return 1
    return 0

In [56]:
df['is_likely_factual'] = df['text'].apply(is_likely_factual)

In [57]:
df_train_v2, df_test_v2 = split_df(df,'label')
result = run_numerical_model(df_train_v2,df_test_v2,'label')
df_train_v2.shape,df_test_v2.shape

((60, 21), (15, 21))

In [58]:
all_result = result['errors_df']
error_only = all_result[all_result['correct'] == False].copy()
error_only

,title,body,code,label,text,title_len,body_len,num_exclamations,questions_per_100_words,has_multiple_paras,...,question_density_per_para,first_person_ratio,is_likely_factual,true_label,pred_label,correct,model,error_type,error_subtype,notes
70,I’m (27f) 80% sure my roommate(30m) wants to s...,"I wanna sleep with him too, honestly he’s tota...",,1,I’m (27f) 80% sure my roommate(30m) wants to s...,58,762,0,0.000000,0,...,0.0,0.120482,0,1,0,False,numerical_only,,,
1,I changed a road sign to make my commute easie...,On my daily commute there was very inconvenien...,,0,I changed a road sign to make my commute easie...,61,1185,0,0.000000,1,...,0.0,0.065385,0,0,2,False,numerical_only,,,
6,What did you gain by getting out of your home ...,,,2,What did you gain by getting out of your home ...,76,0,0,1.333333,0,...,1.0,0.000000,0,2,1,False,numerical_only,,,
66,19F Exhausted New mom not much help from parents.,"Hi i'm a 19f new mom, and I gave birth to my d...",,2,19F Exhausted New mom not much help from paren...,49,1093,0,0.000000,1,...,0.0,0.094170,0,2,0,False,numerical_only,,,
71,"Vegas didn’t evolve, it got murdered by MGM an...","Old Vegas: mob skimmed the drop, but drinks we...",,1,"Vegas didn’t evolve, it got murdered by MGM an...",78,889,0,0.000000,1,...,0.0,0.005435,0,1,2,False,numerical_only,,,
39,What's a subtle sign that someone has high emo...,We always hear the big ones like they're good ...,,2,What's a subtle sign that someone has high emo...,66,396,0,1.333333,1,...,0.5,0.035294,1,2,0,False,numerical_only,,,
42,Where did the girls on Epstein's Island come f...,,,0,Where did the girls on Epstein's Island come f...,96,0,0,4.000000,0,...,3.0,0.000000,0,0,2,False,numerical_only,,,
20,"Why are you on Reddit right now, on Christmas ...",,,0,"Why are you on Reddit right now, on Christmas ...",50,0,0,1.333333,0,...,1.0,0.000000,0,0,1,False,numerical_only,,,

In [59]:
k_fold_fe_1 = evaluate_model_with_feature_and_changes(df,'label','is_likely_factual')

In [60]:
print(f"overall accuracy with feature: {k_fold_fe_1['overall_accuracy_with_feature']}")
print(f"Overall accuracy without feature: {k_fold_fe_1['overall_accuracy_without_feature']}")
print(f"Feature only accuracy with feature: {k_fold_fe_1['open_ended_accuracy_with_feature']}")
print(f"Feature only accuracy without feature: {k_fold_fe_1['open_ended_accuracy_without_feature']}")

overall accuracy with feature: 0.4533333333333333
Overall accuracy without feature: 0.48
Feature only accuracy with feature: 0.8333333333333334
Feature only accuracy without feature: 1.0

In [61]:
k_fold_fe_1['changed_predictions_df']

,title,body,is_likely_factual,true_label,pred_without_feature,pred_with_feature,fold
39,What's a subtle sign that someone has high emo...,We always hear the big ones like they're good ...,1,2,2,0,0
20,"Why are you on Reddit right now, on Christmas ...",,0,0,0,1,1

### Feature Experiment Result: `is_likely_factual`

This feature attempted to distinguish factual vs discussion posts using title
prefix heuristics. Cross-validation showed minimal behavioral change (2 rows),
both of which degraded prediction quality.

Analysis indicates that factual vs discussion intent is a pragmatic distinction
that cannot be reliably captured by lexical prefixes alone. The feature is
therefore rejected.

This confirms a Category D representational gap rather than a feature-label
mismatch.

## Re-running CV After Label Correction

After identifying and correcting Category-A (label ambiguity) errors,
I regenerated the dataset as `post_data_v3.json`.

All prior error patterns were considered unreliable due to label noise.

I will re-run 5-fold Stratified CV using the same model and features to:
- isolate model-induced errors
- avoid contamination from incorrect labels
- rebuild the error taxonomy from clean ground truth

Only errors from this re-evaluation are used for feature design.

In [62]:
df

,title,body,code,label,text,title_len,body_len,num_exclamations,questions_per_100_words,has_multiple_paras,...,log_num_para,word_count,avg_word_len,unique_word_ratio,has_code,log_btt,log_btt_x_has_questions,question_density_per_para,first_person_ratio,is_likely_factual
0,Why are genetic differences in appearance and ...,"I mean, different human races have lived in di...",,1,Why are genetic differences in appearance and ...,188,210,0,2.666667,0,...,0.693147,63,5.349206,0.777778,0,0.110111,0.110111,2.0,0.015625,0
1,I changed a road sign to make my commute easie...,On my daily commute there was very inconvenien...,,0,I changed a road sign to make my commute easie...,61,1185,0,0.000000,1,...,1.791759,255,3.894118,0.552941,0,2.951207,0.000000,0.0,0.065385,0
2,What’s a skill that sounds boring but is actua...,"Some skills don’t sound exciting at first, but...",,1,What’s a skill that sounds boring but is actua...,58,309,0,1.333333,0,...,0.693147,62,4.951613,0.806452,0,1.659035,1.659035,1.0,0.014925,0
3,I can post!,So...\n😭💔😶‍🌫️🥱😮‍💨🙄😒😓😥☹️\nI'm tired.,,0,I can post!\n\nSo...\n😭💔😶‍🌫️🥱😮‍💨🙄😒😓😥☹️\nI'm ti...,11,33,1,0.000000,1,...,1.386294,7,5.571429,1.000000,0,1.041454,0.000000,0.0,0.285714,0
4,My biggest fear is Alzheimer’s,"Not for me, for my mom.\nI don’t think I could...",,0,"My biggest fear is Alzheimer’s\n\nNot for me, ...",30,133,0,0.000000,1,...,1.098612,33,4.000000,0.787879,0,1.463853,0.000000,0.0,0.142857,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,I’m (27f) 80% sure my roommate(30m) wants to s...,"I wanna sleep with him too, honestly he’s tota...",,1,I’m (27f) 80% sure my roommate(30m) wants to s...,58,762,0,0.000000,0,...,0.693147,157,4.235669,0.719745,0,2.559721,0.000000,0.0,0.120482,0
71,"Vegas didn’t evolve, it got murdered by MGM an...","Old Vegas: mob skimmed the drop, but drinks we...",,1,"Vegas didn’t evolve, it got murdered by MGM an...",78,889,0,0.000000,1,...,1.791759,179,4.413408,0.698324,0,2.421774,0.000000,0.0,0.005435,0
72,Beginner Next.js Authentication Project — Look...,Hi everyone 👋\n\nI’m currently learning Next.j...,,1,Beginner Next.js Authentication Project — Look...,83,957,1,0.000000,1,...,3.295837,147,6.034014,0.768707,0,2.434031,0.000000,0.0,0.044872,0
73,Say something in a language other than English...,,,0,Say something in a language other than English...,92,0,0,0.000000,0,...,0.693147,17,4.470588,0.941176,0,-4.532599,-0.000000,0.0,0.000000,0
74,Add a festive snow effect this Christmas with ...,Hello r/reactjs!\n\nSprinkling some snow acros...,import { SnowOverlay } from 'react-snow-overla...,0,Add a festive snow effect this Christmas with ...,68,502,2,0.000000,1,...,2.302585,87,5.528736,0.839080,1,1.986484,0.000000,0.0,0.037736,0