In [2]:
import json
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import random

### Goal of this experiment:
**Teach the model**: Some short questions are still discussion-worthy if they are open-ended

#### Operational definition:
A question is open-ended if:
* It does not have a single factual answer
* It invites opinions, belief, or speculation.

**Examples:**
* What do you think comes after death?(Open ended)
* What is the boiling point of water?(factual)

In [3]:
df = pd.read_csv('../data/post_quality/processed/post_quality_v1.csv')

In [4]:
df.head(5)

,title,body,code,label,text,title_len,body_len,num_exclamations,has_multiple_paras,has_exclamations,questions_per_100_words,log_num_para,word_count,avg_word_len,unique_word_ratio,has_code,log_btt,log_btt_x_has_questions,question_density_per_para,first_person_ratio
0,Why do some people in 2025 still believe that ...,NaN,NaN,1,Why do some people in 2025 still believe that ...,155,0,0,0,0,1.587302,0.693147,31,4.032258,0.935484,0,-5.049856,-5.049856,1.0,0.0
1,If the Rebels had destroyed the Death Star pri...,NaN,NaN,1,If the Rebels had destroyed the Death Star pri...,243,0,0,0,0,0.000000,0.693147,38,5.421053,0.842105,0,-5.497168,-0.000000,0.0,0.0
2,Blacked out and ruined my college life.,"I (18,m) was always a very social kind of pers...",NaN,1,Blacked out and ruined my college life.\n\nI (...,39,1817,0,1,0,1.587302,1.791759,342,4.432749,0.587719,0,3.816613,3.816613,0.2,0.0
3,What’s a subtle sign of very low intelligence?,I’ve been thinking about this lately and wante...,NaN,1,What’s a subtle sign of very low intelligence?...,46,229,0,0,0,3.174603,0.693147,44,5.295455,0.863636,0,1.587932,1.587932,2.0,0.0
4,"""American Problems"" which doesn't exist anywhe...",Have noticed most of the americans are having ...,NaN,0,"""American Problems"" which doesn't exist anywhe...",54,175,0,0,0,3.174603,0.693147,36,5.416667,0.916667,0,1.163151,1.163151,2.0,0.0

In [5]:
for col in df.columns:
    print(f"Number of null value in '{col}' column is {df[col].isnull().sum()}")

Number of null value in 'title' column is 0
Number of null value in 'body' column is 14
Number of null value in 'code' column is 57
Number of null value in 'label' column is 0
Number of null value in 'text' column is 0
Number of null value in 'title_len' column is 0
Number of null value in 'body_len' column is 0
Number of null value in 'num_exclamations' column is 0
Number of null value in 'has_multiple_paras' column is 0
Number of null value in 'has_exclamations' column is 0
Number of null value in 'questions_per_100_words' column is 0
Number of null value in 'log_num_para' column is 0
Number of null value in 'word_count' column is 0
Number of null value in 'avg_word_len' column is 0
Number of null value in 'unique_word_ratio' column is 0
Number of null value in 'has_code' column is 0
Number of null value in 'log_btt' column is 0
Number of null value in 'log_btt_x_has_questions' column is 0
Number of null value in 'question_density_per_para' column is 0
Number of null value in 'first_person_ratio' column is 0

In [6]:
df['body'] = df['body'].fillna('')
df['code'] = df['code'].fillna('')

In [7]:
for col in df.columns:
    print(f"Number of null value in '{col}' column is {df[col].isnull().sum()}")

Number of null value in 'title' column is 0
Number of null value in 'body' column is 0
Number of null value in 'code' column is 0
Number of null value in 'label' column is 0
Number of null value in 'text' column is 0
Number of null value in 'title_len' column is 0
Number of null value in 'body_len' column is 0
Number of null value in 'num_exclamations' column is 0
Number of null value in 'has_multiple_paras' column is 0
Number of null value in 'has_exclamations' column is 0
Number of null value in 'questions_per_100_words' column is 0
Number of null value in 'log_num_para' column is 0
Number of null value in 'word_count' column is 0
Number of null value in 'avg_word_len' column is 0
Number of null value in 'unique_word_ratio' column is 0
Number of null value in 'has_code' column is 0
Number of null value in 'log_btt' column is 0
Number of null value in 'log_btt_x_has_questions' column is 0
Number of null value in 'question_density_per_para' column is 0
Number of null value in 'first_person_ratio' column is 0

In [9]:
df.head(5)

,title,body,code,label,text,title_len,body_len,num_exclamations,has_multiple_paras,has_exclamations,questions_per_100_words,log_num_para,word_count,avg_word_len,unique_word_ratio,has_code,log_btt,log_btt_x_has_questions,question_density_per_para,first_person_ratio
0,Why do some people in 2025 still believe that ...,,,1,Why do some people in 2025 still believe that ...,155,0,0,0,0,1.587302,0.693147,31,4.032258,0.935484,0,-5.049856,-5.049856,1.0,0.0
1,If the Rebels had destroyed the Death Star pri...,,,1,If the Rebels had destroyed the Death Star pri...,243,0,0,0,0,0.000000,0.693147,38,5.421053,0.842105,0,-5.497168,-0.000000,0.0,0.0
2,Blacked out and ruined my college life.,"I (18,m) was always a very social kind of pers...",,1,Blacked out and ruined my college life.\n\nI (...,39,1817,0,1,0,1.587302,1.791759,342,4.432749,0.587719,0,3.816613,3.816613,0.2,0.0
3,What’s a subtle sign of very low intelligence?,I’ve been thinking about this lately and wante...,,1,What’s a subtle sign of very low intelligence?...,46,229,0,0,0,3.174603,0.693147,44,5.295455,0.863636,0,1.587932,1.587932,2.0,0.0
4,"""American Problems"" which doesn't exist anywhe...",Have noticed most of the americans are having ...,,0,"""American Problems"" which doesn't exist anywhe...",54,175,0,0,0,3.174603,0.693147,36,5.416667,0.916667,0,1.163151,1.163151,2.0,0.0

In [10]:
## Let's build a helper function to make error_df
import pandas as pd

def build_error_df(df_test, y_true, y_pred, model_name):
    out = df_test.copy()
    out['true_label'] = y_true
    out['pred_label'] = y_pred
    out['correct'] = y_true == y_pred
    out['model'] = model_name
    return out

In [11]:
## Generic function to split df in same test and train
from sklearn.model_selection import train_test_split


def split_df(
    df,
    label_col,
    test_size=0.2,
    random_state=52,
    stratify=True
):
    """
    Splits dataframe into train and test sets.

    Returns
    -------
    df_train : pd.DataFrame
    df_test : pd.DataFrame
    """

    df = df.reset_index(drop=True)

    stratify_col = df[label_col] if stratify else None

    train_idx, test_idx = train_test_split(
        df.index,
        test_size=test_size,
        random_state=random_state,
        stratify=stratify_col
    )

    df_train = df.loc[train_idx]
    df_test = df.loc[test_idx]

    return df_train, df_test

In [12]:
## Running numerical only model
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report


def run_numerical_model(
    df_train,
    df_test,
    label_col,
    num_cols=None,
    model=None,
    scaler=None,
    model_name="numerical_only"
):
    """
    Trains and evaluates a numerical-only classification model.

    Returns
    -------
    dict with:
        - model
        - scaler
        - classification_report
        - errors_df
        - y_pred
    """

    if num_cols is None:
        num_cols = df_train.select_dtypes(include="number").columns.tolist()
        num_cols.remove(label_col)

    if scaler is None:
        scaler = StandardScaler()

    if model is None:
        model = LogisticRegression(
            max_iter=2000,
            class_weight="balanced"
        )

    X_train = scaler.fit_transform(df_train[num_cols])
    X_test = scaler.transform(df_test[num_cols])

    y_train = df_train[label_col]
    y_test = df_test[label_col]

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    report = classification_report(y_test, y_pred)

    errors_df = build_error_df(
        df_test=df_test,
        y_true=y_test,
        y_pred=y_pred,
        model_name=model_name
    )

    errors_df['error_type'] = ''
    errors_df['error_subtype'] = ''
    errors_df['notes'] = ''

    return {
        "model": model,
        "scaler": scaler,
        "classification_report": report,
        "errors_df": errors_df,
        "y_pred": y_pred
    }

In [13]:
error_all = pd.read_csv("../data/post_quality/processed/numerical_error_taxonomy_v1.csv")
error_all

,title,body,code,label,text,title_len,body_len,num_exclamations,has_multiple_paras,has_exclamations,...,log_btt_x_has_questions,question_density_per_para,first_person_ratio,true_label,pred_label,correct,model,error_type,error_subtype,notes
0,"Be honest, what do you think comes after death?",NaN,NaN,1,"Be honest, what do you think comes after death...",47,0,0,0,0,...,-3.871201,1.0,0.0,1,0,False,numerical_only,B,"""Open question undervalued""","""The numerical-only model over-penalizes short..."
1,"""American Problems"" which doesn't exist anywhe...",Have noticed most of the americans are having ...,NaN,0,"""American Problems"" which doesn't exist anywhe...",54,175,0,0,0,...,1.163151,2.0,0.0,0,2,False,numerical_only,B,"""Context mistaken as depth""","""The numerical-only model incorrectly treats c..."
2,Living in a foreign country is taking its tow,"I love the country I choose to live, since it ...",NaN,1,Living in a foreign country is taking its tow\...,45,285,0,1,0,...,0.000000,0.0,0.0,1,0,False,numerical_only,B,"""Implicit advice ignored""","""The numerical-only model treats the absence o..."
3,CMV: I believe a big majority of social media ...,I think a lot of bad or overtly loud internet ...,NaN,2,CMV: I believe a big majority of social media ...,69,625,0,0,0,...,0.000000,0.0,0.0,2,1,False,numerical_only,B,"""Opinion framed as vagueness""","""The numerical-only model fails to properly we..."

In [16]:
for col in error_all.columns:
    print(f"Number of null value in '{col}' column is {error_all[col].isnull().sum()}")

Number of null value in 'title' column is 0
Number of null value in 'body' column is 1
Number of null value in 'code' column is 4
Number of null value in 'label' column is 0
Number of null value in 'text' column is 0
Number of null value in 'title_len' column is 0
Number of null value in 'body_len' column is 0
Number of null value in 'num_exclamations' column is 0
Number of null value in 'has_multiple_paras' column is 0
Number of null value in 'has_exclamations' column is 0
Number of null value in 'questions_per_100_words' column is 0
Number of null value in 'log_num_para' column is 0
Number of null value in 'word_count' column is 0
Number of null value in 'avg_word_len' column is 0
Number of null value in 'unique_word_ratio' column is 0
Number of null value in 'has_code' column is 0
Number of null value in 'log_btt' column is 0
Number of null value in 'log_btt_x_has_questions' column is 0
Number of null value in 'question_density_per_para' column is 0
Number of null value in 'first_person_ratio' column is 0
Number of null value in 'true_label' column is 0
Number of null value in 'pred_label' column is 0
Number of null value in 'correct' column is 0
Number of null value in 'model' column is 0
Number of null value in 'error_type' column is 0
Number of null value in 'error_subtype' column is 0
Number of null value in 'notes' column is 0

In [17]:
error_all['body'] = error_all['body'].fillna('')
error_all['code'] = error_all['code'].fillna('')

In [18]:
for col in error_all.columns:
    print(f"Number of null value in '{col}' column is {error_all[col].isnull().sum()}")

Number of null value in 'title' column is 0
Number of null value in 'body' column is 0
Number of null value in 'code' column is 0
Number of null value in 'label' column is 0
Number of null value in 'text' column is 0
Number of null value in 'title_len' column is 0
Number of null value in 'body_len' column is 0
Number of null value in 'num_exclamations' column is 0
Number of null value in 'has_multiple_paras' column is 0
Number of null value in 'has_exclamations' column is 0
Number of null value in 'questions_per_100_words' column is 0
Number of null value in 'log_num_para' column is 0
Number of null value in 'word_count' column is 0
Number of null value in 'avg_word_len' column is 0
Number of null value in 'unique_word_ratio' column is 0
Number of null value in 'has_code' column is 0
Number of null value in 'log_btt' column is 0
Number of null value in 'log_btt_x_has_questions' column is 0
Number of null value in 'question_density_per_para' column is 0
Number of null value in 'first_person_ratio' column is 0
Number of null value in 'true_label' column is 0
Number of null value in 'pred_label' column is 0
Number of null value in 'correct' column is 0
Number of null value in 'model' column is 0
Number of null value in 'error_type' column is 0
Number of null value in 'error_subtype' column is 0
Number of null value in 'notes' column is 0

In [19]:
error_all.shape

(4, 27)

In [20]:
error_all[error_all['error_subtype']=="\"Open question undervalued\""]

,title,body,code,label,text,title_len,body_len,num_exclamations,has_multiple_paras,has_exclamations,...,log_btt_x_has_questions,question_density_per_para,first_person_ratio,true_label,pred_label,correct,model,error_type,error_subtype,notes
0,"Be honest, what do you think comes after death?",,,1,"Be honest, what do you think comes after death...",47,0,0,0,0,...,-3.871201,1.0,0.0,1,0,False,numerical_only,B,"""Open question undervalued""","""The numerical-only model over-penalizes short..."

In [21]:
OPEN_ENDED_PHRASES = [
    # Opinions & beliefs
    "what do you think",
    "what are your thoughts",
    "what is your perspective",
    "how would you describe",
    "in your opinion",
    "do you believe",
    "do you think that",
    "would you say that",

    # Feelings & reactions
    "how do you feel",
    "how does it make you feel",
    "what was your reaction",
    "what stood out to you",
    "how did it affect you",

    # Reasons & explanations
    "why do people",
    "why do we",
    "why do you think",
    "what do you think causes",
    "what leads people to",
    "what might explain",

    # Processes & behavior
    "how do people",
    "how do you usually",
    "how does this work",
    "how would someone",
    "what typically happens",

    # Possibilities & outcomes
    "what could happen",
    "what do you expect",
    "what comes after",
    "what might come next",
    "where do you see this going",

    # Reflection & evaluation
    "what does this mean to you",
    "how would you evaluate",
    "what matters most to you",
    "what do you find important",
    "what do you think is missing",

    # Comparisons & alternatives
    "how is this different from",
    "how is this similar to",
    "what other options are there",
    "what alternatives can you imagine",

    # Personal experience
    "have you ever noticed",
    "have you experienced",
    "what has your experience been",
    "can you tell me about",

    # Clarification & exploration
    "can you explain more",
    "can you elaborate",
    "what do you mean by",
    "how would you clarify"
]

In [22]:
def is_open_ended_question(title:str, body:str):
    text = (title + " " + body).lower()

    if "?" not in text:
        return 0
    
    for phrase in OPEN_ENDED_PHRASES:
        if phrase in text:
            return 1
    
    return 0

In [23]:
df['is_open_ended_question'] = df.apply(
    lambda row: is_open_ended_question(
        str(row['title']) if pd.notna(row['title']) else "",
        str(row['body']) if pd.notna(row['body']) else ""
    ),
    axis=1
)

In [24]:
df[df['is_open_ended_question'] == 1]

,title,body,code,label,text,title_len,body_len,num_exclamations,has_multiple_paras,has_exclamations,...,log_num_para,word_count,avg_word_len,unique_word_ratio,has_code,log_btt,log_btt_x_has_questions,question_density_per_para,first_person_ratio,is_open_ended_question
35,"Be honest, what do you think comes after death?",,,1,"Be honest, what do you think comes after death...",47,0,0,0,0,...,0.693147,9,4.333333,1.0,0,-3.871201,-3.871201,1.0,0.0,1

In [25]:
df_train_generic, df_test_generic = split_df(df,'label')
result_num_v2 = run_numerical_model(df_train_generic,df_test_generic,'label')

In [26]:
wrong_num_v2 = result_num_v2['errors_df']
wrong_num_v2[wrong_num_v2['correct']==False]

,title,body,code,label,text,title_len,body_len,num_exclamations,has_multiple_paras,has_exclamations,...,question_density_per_para,first_person_ratio,is_open_ended_question,true_label,pred_label,correct,model,error_type,error_subtype,notes
35,"Be honest, what do you think comes after death?",,,1,"Be honest, what do you think comes after death...",47,0,0,0,0,...,1.0,0.0,1,1,0,False,numerical_only,,,
4,"""American Problems"" which doesn't exist anywhe...",Have noticed most of the americans are having ...,,0,"""American Problems"" which doesn't exist anywhe...",54,175,0,0,0,...,2.0,0.0,0,0,2,False,numerical_only,,,
27,Living in a foreign country is taking its tow,"I love the country I choose to live, since it ...",,1,Living in a foreign country is taking its tow\...,45,285,0,1,0,...,0.0,0.0,0,1,0,False,numerical_only,,,
22,CMV: I believe a big majority of social media ...,I think a lot of bad or overtly loud internet ...,,2,CMV: I believe a big majority of social media ...,69,625,0,0,0,...,0.0,0.0,0,2,1,False,numerical_only,,,

### Observation: There is only one post for which `is_open_ended_question` has given 1. So there is no way model can train and test. I am marking this error as **Category C** for now and let's get 6-10 more posts of same type and do feature engineering v_2, for it and save in **post_quality_v2.csv** file, and check **post_data_v2.json**

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   title                      63 non-null     object
 1   body                       63 non-null     object
 2   code                       63 non-null     object
 3   label                      63 non-null     int64
 4   text                       63 non-null     object
 5   title_len                  63 non-null     int64
 6   body_len                   63 non-null     int64
 7   num_exclamations           63 non-null     int64
 8   has_multiple_paras         63 non-null     int64
 9   has_exclamations           63 non-null     int64
 10  questions_per_100_words    63 non-null     float64
 11  log_num_para               63 non-null     float64
 12  word_count                 63 non-null     int64
 13  avg_word_len               63 non-null     float64
 14  unique_word_ratio          63 non-null     float64
 15  has_code                   63 non-null     int64
 16  log_btt                    63 non-null     float64
 17  log_btt_x_has_questions    63 non-null     float64
 18  question_density_per_para  63 non-null     float64
 19  first_person_ratio         63 non-null     float64
 20  is_open_ended_question     63 non-null     int64
dtypes: float64(8), int64(9), object(4)
memory usage: 10.5+ KB

In [28]:
df.to_csv("../data/post_quality/processed/post_quality_v1_1.csv",index=False)